/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.ProjectController;
import javax.swing.JOptionPane;
import model.ProjectModel;

/**
 *
 * @author kelson
 */
public class ProjectDialogScreen extends javax.swing.JDialog {

    ProjectController controller;
    
    public ProjectDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        controller = new ProjectController();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanelAddProjectHeader = new javax.swing.JPanel();
        jPanelAddProjectHeaderTitle = new javax.swing.JLabel();
        jPanelAddProjectHeaderIcon = new javax.swing.JLabel();
        jPanelAddProjectPanel = new javax.swing.JPanel();
        jPanelAddProjectPanelNameLabel = new javax.swing.JLabel();
        jPanelAddProjectPanelNameInput = new javax.swing.JTextField();
        jPanelAddProjectPanelDescLabel = new javax.swing.JLabel();
        jPanelAddProjectPanelDescInput = new javax.swing.JScrollPane();
        jPanelAddProjectPanelDescInputText = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(300, 600));

        jPanelAddProjectHeader.setBackground(new java.awt.Color(0, 153, 102));

        jPanelAddProjectHeaderTitle.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jPanelAddProjectHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAddProjectHeaderTitle.setText("Adicionar Projeto");

        jPanelAddProjectHeaderIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelAddProjectHeaderIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check3.png"))); // NOI18N
        jPanelAddProjectHeaderIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAddProjectHeaderIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelAddProjectHeaderLayout = new javax.swing.GroupLayout(jPanelAddProjectHeader);
        jPanelAddProjectHeader.setLayout(jPanelAddProjectHeaderLayout);
        jPanelAddProjectHeaderLayout.setHorizontalGroup(
            jPanelAddProjectHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddProjectHeaderLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanelAddProjectHeaderTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAddProjectHeaderIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelAddProjectHeaderLayout.setVerticalGroup(
            jPanelAddProjectHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAddProjectHeaderIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
            .addComponent(jPanelAddProjectHeaderTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelAddProjectPanel.setBackground(java.awt.Color.white);

        jPanelAddProjectPanelNameLabel.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jPanelAddProjectPanelNameLabel.setText("Nome:");

        jPanelAddProjectPanelNameInput.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jPanelAddProjectPanelNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPanelAddProjectPanelNameInputActionPerformed(evt);
            }
        });

        jPanelAddProjectPanelDescLabel.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jPanelAddProjectPanelDescLabel.setText("Descrição:");

        jPanelAddProjectPanelDescInputText.setColumns(20);
        jPanelAddProjectPanelDescInputText.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jPanelAddProjectPanelDescInputText.setRows(5);
        jPanelAddProjectPanelDescInput.setViewportView(jPanelAddProjectPanelDescInputText);

        javax.swing.GroupLayout jPanelAddProjectPanelLayout = new javax.swing.GroupLayout(jPanelAddProjectPanel);
        jPanelAddProjectPanel.setLayout(jPanelAddProjectPanelLayout);
        jPanelAddProjectPanelLayout.setHorizontalGroup(
            jPanelAddProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddProjectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAddProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAddProjectPanelDescInput, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                    .addComponent(jPanelAddProjectPanelNameInput)
                    .addComponent(jPanelAddProjectPanelNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAddProjectPanelDescLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelAddProjectPanelLayout.setVerticalGroup(
            jPanelAddProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddProjectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAddProjectPanelNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAddProjectPanelNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelAddProjectPanelDescLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAddProjectPanelDescInput, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAddProjectHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanelAddProjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelAddProjectHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelAddProjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelAddProjectPanelNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPanelAddProjectPanelNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelAddProjectPanelNameInputActionPerformed

    private void jPanelAddProjectHeaderIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAddProjectHeaderIconMouseClicked
        // TODO add your handling code here:
        try {
            if(!jPanelAddProjectPanelNameInput.getText().equals("")) {
                ProjectModel project = new ProjectModel();
                project.setName(jPanelAddProjectPanelNameInput.getText());
                project.setDescription(jPanelAddProjectPanelDescInputText.getText());
                controller.create(project);
                JOptionPane.showMessageDialog(rootPane, "Projeto criado com sucesso!");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "O nome é obrigatório!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
            this.dispose();
        }
    }//GEN-LAST:event_jPanelAddProjectHeaderIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProjectDialogScreen dialog = new ProjectDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelAddProjectHeader;
    private javax.swing.JLabel jPanelAddProjectHeaderIcon;
    private javax.swing.JLabel jPanelAddProjectHeaderTitle;
    private javax.swing.JPanel jPanelAddProjectPanel;
    private javax.swing.JScrollPane jPanelAddProjectPanelDescInput;
    private javax.swing.JTextArea jPanelAddProjectPanelDescInputText;
    private javax.swing.JLabel jPanelAddProjectPanelDescLabel;
    private javax.swing.JTextField jPanelAddProjectPanelNameInput;
    private javax.swing.JLabel jPanelAddProjectPanelNameLabel;
    // End of variables declaration//GEN-END:variables
}
