/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.TaskController;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.ProjectModel;
import model.TaskModel;

/**
 *
 * @author kelson
 */
public class TaskDialogScreen extends javax.swing.JDialog {

    TaskController controller;
    ProjectModel projectModel;
    
    public TaskDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        hideErrorFields();
        
        controller = new TaskController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAddTaskHeader = new javax.swing.JPanel();
        jPanelAddTaskHeaderTitle = new javax.swing.JLabel();
        jPanelAddTaskHeaderIcon = new javax.swing.JLabel();
        jPanelAddTaskPanel = new javax.swing.JPanel();
        jPanelAddTaskPanelNameLabel = new javax.swing.JLabel();
        jPanelAddTaskPanelNameInput = new javax.swing.JTextField();
        jPanelAddTaskPanelDescLabel = new javax.swing.JLabel();
        jPanelAddTaskPanelDescInput = new javax.swing.JScrollPane();
        jPanelAddTaskPanelDescInputText = new javax.swing.JTextArea();
        jPanelAddTaskPanelDeadlineLabel = new javax.swing.JLabel();
        jFormattedAddTaskPanelDeadlineInput = new javax.swing.JFormattedTextField();
        jPanelAddTaskPanelNotesLabel = new javax.swing.JLabel();
        jPanelAddTaskPanelNotesInput = new javax.swing.JScrollPane();
        jPanelAddTaskPanelNotesInputText = new javax.swing.JTextArea();
        jFieldNameRequired = new javax.swing.JLabel();
        jFieldDeadlineRequired = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(300, 600));

        jPanelAddTaskHeader.setBackground(new java.awt.Color(0, 153, 102));

        jPanelAddTaskHeaderTitle.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jPanelAddTaskHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        jPanelAddTaskHeaderTitle.setText("Adicionar Tarefa");

        jPanelAddTaskHeaderIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelAddTaskHeaderIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check3.png"))); // NOI18N
        jPanelAddTaskHeaderIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAddTaskHeaderIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelAddTaskHeaderLayout = new javax.swing.GroupLayout(jPanelAddTaskHeader);
        jPanelAddTaskHeader.setLayout(jPanelAddTaskHeaderLayout);
        jPanelAddTaskHeaderLayout.setHorizontalGroup(
            jPanelAddTaskHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddTaskHeaderLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanelAddTaskHeaderTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAddTaskHeaderIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelAddTaskHeaderLayout.setVerticalGroup(
            jPanelAddTaskHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAddTaskHeaderIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
            .addComponent(jPanelAddTaskHeaderTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelAddTaskPanel.setBackground(java.awt.Color.white);

        jPanelAddTaskPanelNameLabel.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jPanelAddTaskPanelNameLabel.setText("Nome:");

        jPanelAddTaskPanelNameInput.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jPanelAddTaskPanelNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPanelAddTaskPanelNameInputActionPerformed(evt);
            }
        });

        jPanelAddTaskPanelDescLabel.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jPanelAddTaskPanelDescLabel.setText("Descrição:");

        jPanelAddTaskPanelDescInputText.setColumns(20);
        jPanelAddTaskPanelDescInputText.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jPanelAddTaskPanelDescInputText.setRows(5);
        jPanelAddTaskPanelDescInput.setViewportView(jPanelAddTaskPanelDescInputText);

        jPanelAddTaskPanelDeadlineLabel.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jPanelAddTaskPanelDeadlineLabel.setText("Prazo:");

        jFormattedAddTaskPanelDeadlineInput.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedAddTaskPanelDeadlineInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedAddTaskPanelDeadlineInputActionPerformed(evt);
            }
        });

        jPanelAddTaskPanelNotesLabel.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jPanelAddTaskPanelNotesLabel.setText("Notas:");

        jPanelAddTaskPanelNotesInputText.setColumns(20);
        jPanelAddTaskPanelNotesInputText.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jPanelAddTaskPanelNotesInputText.setRows(5);
        jPanelAddTaskPanelNotesInput.setViewportView(jPanelAddTaskPanelNotesInputText);

        jFieldNameRequired.setForeground(new java.awt.Color(255, 0, 0));
        jFieldNameRequired.setText("* Campo obrigatório");

        jFieldDeadlineRequired.setForeground(new java.awt.Color(255, 0, 0));
        jFieldDeadlineRequired.setText("* Campo obrigatório");

        javax.swing.GroupLayout jPanelAddTaskPanelLayout = new javax.swing.GroupLayout(jPanelAddTaskPanel);
        jPanelAddTaskPanel.setLayout(jPanelAddTaskPanelLayout);
        jPanelAddTaskPanelLayout.setHorizontalGroup(
            jPanelAddTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddTaskPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAddTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAddTaskPanelDescInput, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                    .addComponent(jPanelAddTaskPanelNameInput)
                    .addComponent(jPanelAddTaskPanelDescLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAddTaskPanelNotesInput)
                    .addComponent(jPanelAddTaskPanelNotesLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFormattedAddTaskPanelDeadlineInput)
                    .addGroup(jPanelAddTaskPanelLayout.createSequentialGroup()
                        .addComponent(jPanelAddTaskPanelNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFieldNameRequired, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelAddTaskPanelLayout.createSequentialGroup()
                        .addComponent(jPanelAddTaskPanelDeadlineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFieldDeadlineRequired, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelAddTaskPanelLayout.setVerticalGroup(
            jPanelAddTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddTaskPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAddTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPanelAddTaskPanelNameLabel)
                    .addComponent(jFieldNameRequired))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAddTaskPanelNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelAddTaskPanelDescLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAddTaskPanelDescInput, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanelAddTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPanelAddTaskPanelDeadlineLabel)
                    .addComponent(jFieldDeadlineRequired))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedAddTaskPanelDeadlineInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelAddTaskPanelNotesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAddTaskPanelNotesInput, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAddTaskHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanelAddTaskPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelAddTaskHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelAddTaskPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelAddTaskPanelNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPanelAddTaskPanelNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelAddTaskPanelNameInputActionPerformed

    private void jFormattedAddTaskPanelDeadlineInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedAddTaskPanelDeadlineInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedAddTaskPanelDeadlineInputActionPerformed

    private void jPanelAddTaskHeaderIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAddTaskHeaderIconMouseClicked
        // TODO add your handling code here:
        
        try {
            String deadlineField = jFormattedAddTaskPanelDeadlineInput.getText();
            String nameField = jPanelAddTaskPanelNameInput.getText();
            
            if(nameField.isEmpty()) {
                // JOptionPane.showMessageDialog(rootPane, "O nome é obrigatório!");
                jFieldNameRequired.setVisible(true);
            } else if(deadlineField.isBlank()) {
                // JOptionPane.showMessageDialog(rootPane, "O prazo é obrigatório!");
                jFieldDeadlineRequired.setVisible(true);
            } else {
                TaskModel task = new TaskModel();
                task.setIdProject(projectModel.getId());
                task.setName(jPanelAddTaskPanelNameInput.getText());
                task.setDescription(jPanelAddTaskPanelDescInputText.getText());
                task.setNotes(jPanelAddTaskPanelNotesInputText.getText());
                task.setFinished(false);

                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                Date deadline = null;
                deadline = dateFormat.parse(jFormattedAddTaskPanelDeadlineInput.getText());
                task.setDeadline(deadline);

                controller.create(task);
                JOptionPane.showMessageDialog(rootPane, "Tarefa adicionada com sucesso!");
                this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
            this.dispose();
        }
    }//GEN-LAST:event_jPanelAddTaskHeaderIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaskDialogScreen dialog = new TaskDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void setProjectModel(ProjectModel projectModel) {
        this.projectModel = projectModel;
    }
    
    public void hideErrorFields() {
        jFieldNameRequired.setVisible(false);
        jFieldDeadlineRequired.setVisible(false);
    }
    
    public boolean isFieldValid() {
        return true;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jFieldDeadlineRequired;
    private javax.swing.JLabel jFieldNameRequired;
    private javax.swing.JFormattedTextField jFormattedAddTaskPanelDeadlineInput;
    private javax.swing.JPanel jPanelAddTaskHeader;
    private javax.swing.JLabel jPanelAddTaskHeaderIcon;
    private javax.swing.JLabel jPanelAddTaskHeaderTitle;
    private javax.swing.JPanel jPanelAddTaskPanel;
    private javax.swing.JLabel jPanelAddTaskPanelDeadlineLabel;
    private javax.swing.JScrollPane jPanelAddTaskPanelDescInput;
    private javax.swing.JTextArea jPanelAddTaskPanelDescInputText;
    private javax.swing.JLabel jPanelAddTaskPanelDescLabel;
    private javax.swing.JTextField jPanelAddTaskPanelNameInput;
    private javax.swing.JLabel jPanelAddTaskPanelNameLabel;
    private javax.swing.JScrollPane jPanelAddTaskPanelNotesInput;
    private javax.swing.JTextArea jPanelAddTaskPanelNotesInputText;
    private javax.swing.JLabel jPanelAddTaskPanelNotesLabel;
    // End of variables declaration//GEN-END:variables
}
